# Criar .env.production automaticamente
$envContent = @"
# Produção - Imobiliária Pharos
NODE_ENV=production
NEXT_PUBLIC_SITE_URL=https://app.pharosnegocios.com.br
VISTA_BASE_URL=https://gabarito-rest.vistahost.com.br
VISTA_API_KEY=CONFIGURE_SUA_CHAVE_AQUI
DWV_BASE_URL=https://agencies.dwvapp.com.br
DWV_API_TOKEN=4b3e322a7773c8b3498606ed5d086a613171c65d542acbacd41b41af51d1d59a
DWV_TIMEOUT_MS=15000
FOTOS_ENDPOINT_ENABLED=false
NEXT_PUBLIC_LISTING_PROVIDER=dual
NEXT_PUBLIC_WHATSAPP_NUMBER=5548999999999
NEXT_PUBLIC_WHATSAPP_MESSAGE=Olá! Gostaria de ver mais fotos do imóvel {CODIGO}.
NEXT_PUBLIC_GTM_ID=
NEXT_PUBLIC_GA_MEASUREMENT_ID=
SSGTM_ENDPOINT_URL=
SSGTM_CONTAINER_CONFIG=
META_PIXEL_ID=
META_CONVERSION_API_TOKEN=
GOOGLE_ANALYTICS_MEASUREMENT_ID=
GOOGLE_ANALYTICS_API_SECRET=
GOOGLE_ADS_CONVERSION_ID=
GOOGLE_ADS_CONVERSION_LABEL=
NEXT_PUBLIC_TURNSTILE_SITE_KEY=
TURNSTILE_SECRET_KEY=
MAUTIC_BASE_URL=
MAUTIC_AUTH_TYPE=basic
MAUTIC_API_USERNAME=
MAUTIC_API_PASSWORD=
MAUTIC_TIMEOUT_MS=30000
C2S_API_URL=https://api.contact2sale.com/integration
C2S_API_TOKEN=
C2S_COMPANY_ID=
C2S_DEFAULT_SELLER_ID=
C2S_WEBHOOK_SECRET=
C2S_TIMEOUT_MS=15000
C2S_RETRY_ATTEMPTS=3
C2S_RETRY_DELAY_MS=1000
C2S_ENABLED=false
C2S_SYNC_SELLERS=false
C2S_AUTO_TAGS=false
C2S_WEBHOOKS_ENABLED=false
C2S_DISTRIBUTION_ENABLED=false
C2S_VISIT_INTEGRATION=false
"@
$envContent | Out-File -FilePath ".env.production" -Encoding UTF8 -NoNewline
Write-Host "✅ .env.production criado"

